#!/usr/bin/env node
// Seed the *local* Miniflare D1 with enough data to play the game end-to-end.
//
//   - admin account  `admin` / `1234`   (PBKDF2-SHA256, 100k iterations)
//   - today's challenge:    대한민국 → 무궁화
//   - tomorrow's challenge: 대한민국 → 무궁화 (for one-click time-travel testing)
//
// Runs via `pnpm --filter @linkle/api run db:seed:local`. The password hash
// is computed fresh on every run and spliced into a SQL file, so the SQL
// itself never sits in the repo with stale creds baked in.

import { spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const ITERATIONS = 100_000;
const enc = new TextEncoder();

function toBase64(bytes) {
  let bin = '';
  for (const b of bytes) bin += String.fromCharCode(b);
  return Buffer.from(bin, 'binary').toString('base64');
}

async function hashPassword(password) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const key = await crypto.subtle.importKey(
    'raw',
    enc.encode(password),
    { name: 'PBKDF2' },
    false,
    ['deriveBits'],
  );
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt, iterations: ITERATIONS, hash: 'SHA-256' },
    key,
    32 * 8,
  );
  return `v1$${ITERATIONS}$${toBase64(salt)}$${toBase64(new Uint8Array(bits))}`;
}

function kstDateOffset(offsetDays) {
  const KST_OFFSET_MS = 9 * 60 * 60 * 1000;
  const ms = Date.now() + offsetDays * 24 * 60 * 60 * 1000;
  const kst = new Date(ms + KST_OFFSET_MS);
  const yyyy = kst.getUTCFullYear();
  const mm = String(kst.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(kst.getUTCDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
}

function sqlEscape(s) {
  return s.replace(/'/g, "''");
}

async function main() {
  const hash = await hashPassword('1234');
  const today = kstDateOffset(0);
  const tomorrow = kstDateOffset(1);
  const now = Date.now();

  const sql = [
    '-- auto-generated by seed-local.mjs; do not commit',
    "INSERT OR REPLACE INTO admins (id, username, password_hash, created_at) VALUES",
    `  ('adm_local', 'admin', '${sqlEscape(hash)}', ${now});`,
    '',
    'INSERT OR REPLACE INTO challenges (date, start_page, end_page, created_at, created_by) VALUES',
    `  ('${today}',    '대한민국', '무궁화', ${now}, 'seed-local'),`,
    `  ('${tomorrow}', '대한민국', '무궁화', ${now}, 'seed-local');`,
    '',
  ].join('\n');

  const dir = mkdtempSync(join(tmpdir(), 'linkle-seed-'));
  const file = join(dir, 'seed.sql');
  writeFileSync(file, sql);

  try {
    console.log(`[seed] applying to local D1:\n${sql}`);
    const res = spawnSync(
      'pnpm',
      ['exec', 'wrangler', 'd1', 'execute', 'linkle-db', '--local', '--file', file],
      { stdio: 'inherit' },
    );
    if (res.status !== 0) process.exit(res.status ?? 1);
    console.log(`[seed] done. admin=admin/1234, challenges ${today}, ${tomorrow}`);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

await main();
